codecov:
  branch: develop

comment:
  layout: 'diff, files'

coverage:
  status:
    project:
      default:
        target: 0%
    patch:
      default:
        target: 90%

github_checks:
  annotations: false
