name: 'Get Runner Environment Version'
description: 'Output runner OS and NodeJS version'
outputs:
  node:
    description: "Node Version"
    value: ${{ steps.output-node-version.outputs.version }}
  os:
    description: "OS Version"
    value: ${{ steps.output-os-version.outputs.version }}
runs:
  using: 'composite'
  steps:
    - name: Output Node version
      id: output-node-version
      run: echo "::set-output name=version::`node -v`"
      shell: bash
    - name: Output OS version
      id: output-os-version
      run: echo "::set-output name=version::`lsb_release -d -s`"
      shell: bash
