extends: ichef

rules:
   "import/extensions": [
      "error",
      "ignorePackages",
      {
        "js": "never",
        "jsx": "never",
        "ts": "never",
        "tsx": "never"
      }
   ]


env:
    browser: true
    es6: true
    jest: true

settings:
    import/resolver:
        babel-module: {}
        typescript: {}

parserOptions:
    sourceType: module
