extends: [
    ichef,
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:import/typescript'
]

parser: '@typescript-eslint/parser'

plugins: [
    '@typescript-eslint'
]

"rules":
   "import/extensions": [
      "error",
      "ignorePackages",
      {
        "js": "never",
        "jsx": "never",
        "ts": "never",
        "tsx": "never"
      }
   ]


env:
    browser: true
    es6: true
    jest: true

settings:
    import/resolver:
        babel-module: {}

parserOptions:
    sourceType: module
