extends: [
    ichef,
    'plugin:@typescript-eslint/eslint-recommended',
]

parser: '@typescript-eslint/parser'

plugins: [
    '@typescript-eslint'
]

env:
    browser: true
    es6: true
    jest: true

settings:
    import/resolver:
        babel-module: {}

parserOptions:
    sourceType: module
