extends: [
    ichef,
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:import/typescript'
]

parser: '@typescript-eslint/parser'

plugins: [
    '@typescript-eslint'
]

rules:
    "import/extensions": [
        "error",
        "ignorePackages",
        {
        "js": "never",
        "jsx": "never",
        "ts": "never",
        "tsx": "never"
        }
    ]
    "no-unused-vars": "off"
    "@typescript-eslint/no-unused-vars": ["error", { "ignoreRestSiblings": true }]


env:
    browser: true
    es6: true
    jest: true

settings:
    import/resolver:
        babel-module: {}

parserOptions:
    sourceType: module
