extends: stylelint-config-standard

configBasedir: ../

rules:
    indentation: 4
    number-leading-zero: never
    selector-pseudo-element-colon-notation: single

ignoreFiles:
    - node_modules/
    - coverage/
    - dist/
