name: Auto Assign Assignees and Reviewers on PR

on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: iCHEF/action-request-review@v1
        with:
          token: ${{ secrets.ICHEF_BOT_TOKEN }}
          config_gist_id: 91ffd6e7318cdf5a02353af0a15e2bcf
