name: 'Auto Assign Assignees and Reviewers on PR'

on:
  pull_request:
    types: 
      - opened
    branches:
      - develop

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
