name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install packages with cache
      uses: './.github/actions/install_package_with_cache'
    - name: Build static assets
      run: yarn build

  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install packages with cache
      uses: './.github/actions/install_package_with_cache'
    - name: Run linter
      run: yarn lint
    - name: Run tests
      run: yarn test
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: "./coverage/coverage-final.json"
